### ISSUE TITLE
Adguard DNS app when enabled causes error when watching vods

### ISSUE THREAD

**Issue by Bareno** [nopbreak/TwitchMod#33]
I get the following error whenever I open up a streamers past broadcast.

`Uncaught Error in Rx stream

io.reactivex.exceptions.OnErrorNotImplementedException: Connection closed by peer
Caused by: javax.net.ssl.SSLHandshakeException: Connection closed by peer
	at tv.twitch.android.shared.player.trackers.PlayerPresenterTracker.trackCountessPlay(PlayerPresenterTracker.kt:4)
	at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
	at [[ ↓↓ Original trace ↓↓ ]].(:0)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:234)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:8)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:9)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:17)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:47)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:1)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:6)
	at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:6)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:5)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:1)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:20)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:1)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:22)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:10)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:6)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:1)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:13)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)`

**Comment by Bareno** [comment]
Update on this... turns out it happens whenever I open a past broadcast. So I was wrong in thinking it was something about the links screwing up.

And forgot to include this,  but I'm using galaxy note 10 plus on android 10

**Comment by Bareno** [comment]
Another update, turns out the ad guard dns adblock app causes this when turned on. Pausing it caused the errors to go away.
